platform: linux

# image: docker:///busybox

image_resource:
  type: docker-image
  source: 
    repository: ['busybox']

inputs:
- name: spring-boot-ci-example
- name: docker-builds-binaries

outputs:
- name: context

run:
  path: spring-boot-ci-example/ci/scripts/create-context.sh
