platform: linux
image_resource:
  type: docker-image
  source: 
    repository: busybox

inputs:
- name: docker-builds-binaries
- name: spring-boot-ci-example

outputs:
- name: context

run:
  path: spring-boot-ci-example/ci/scripts/create-context.sh
